#!/bin/bash

stl="$1"
z="$2"

if [ $# -lt 2 ] ; then
	echo "Usage $0 STL Z-height"
	exit 5
fi
if [ x"$stl" = x"" ] ; then
	echo "STL file is required"
	exit 1
fi
if [ x"$z" = x"" ] ; then
	echo "Inform Z height to pause after"
	exit 2
fi

if grep -q "after_z:${z}$" "$stl" ; then
	sed -i -e "s/after_z:${z}$/after_z:${z}\nM25 ; pause after ${z}/" "$stl"
	echo "Current pauses"
	grep -n -B 1 "^M25" "$stl"
else
	echo "Layer not found (after_z:${z})"
	exit 3
fi
